In [5]:
import numpy as np

y_predicted = np.array([1,1,0,0,1,0,1,0,0,1])
y_true = np.array([0.30,0.70,1,0,0.5,0.3,0.8,0.7,0.2,0.4])

In [19]:
# mean absolute error
def mae(y_true,y_predicted):
    total_error = 0
    for yt, yp in zip(y_true,y_predicted):
        total_error += np.abs(yt - yp)
    print(f"total error: {total_error}")
    
    mae = total_error / len(y_true)
    print(f"mean absolute error : {mae}")
    return mae

In [20]:
mae(y_true,y_predicted)

total error: 4.5
mean absolute error : 0.45


0.45

In [22]:
# mean absolute error in one line using numpy
np.mean(np.abs(y_predicted-y_true))

0.45

In [46]:
# mean square error in one line using numpy
np.mean(np.square(y_predicted-y_true))

0.28500000000000003

In [27]:
np.log([0.000000000000000000001])

array([-48.35428695])

In [37]:
epsilon = 1e-15
epsilon

1e-15

In [30]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]

In [31]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999,
 0.999999999999999,
 1e-15,
 1e-15,
 0.999999999999999,
 1e-15,
 0.999999999999999,
 1e-15,
 1e-15,
 0.999999999999999]

In [32]:
y_predicted_new = np.array(y_predicted_new)
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00, 1.e-15, 1.e+00, 1.e-15,
       1.e-15, 1.e+00])

In [33]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16, -3.45387764e+01, -9.99200722e-16, -3.45387764e+01,
       -3.45387764e+01, -9.99200722e-16])

In [34]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

15.54263328511875

In [44]:
# log loss error count
def log_loss(y_true,y_predicted):
    # replace 0 to close value of zero
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    # replace 1 to close value of one
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    # we can not apply log loss diractly to the list so we have to convert numpy array
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [45]:
log_loss(y_true,y_predicted)

15.54263328511875