In [1]:
import numpy as np

In [2]:
revenue = np.array([[100,200,220],[24,36,40],[12,80,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit = revenue - expenses

In [4]:
profit

array([[ 20, 110, 120],
       [ 14,  20,  20],
       [  4,  70,  10]])

In [7]:
price_per_unit = np.array([[1000,400,1200]])
unit = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [8]:
price_per_unit * unit

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [12]:
revenue_d = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
inr = np.array([75])
revenue_d*inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [14]:
units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])

In [15]:
total_sales_amount = np.dot(price_per_unit,units_sold)
total_sales_amount

array([1900, 2640, 1430])